require 'rubocop/rake_task'

RuboCop::RakeTask.new

begin
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:spec) do |t|
    t.rspec_opts = '--format doc --color'
  end
  rescue LoadError
end

