require 'rubocop/rake_task'

RuboCop::RakeTask.new

begin
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:spec) do |t|
    t.rspec_opts = '--format doc --color'
  end
  rescue LoadError
end

desc 'list files from path using provided pattern or defaulting to listing all files'
task :list, [:path, :pattern] do |t, args|

  pattern = args[:pattern] ||= "*.*"

  Dir.chdir args[:path]
  files = Rake::FileList[pattern]
  puts files
end

task default: %w[spec rubocop:auto_correct]

desc 'reverts changes made by running rubocop:auto_correct'
task :revert_auto_correct do
  sh 'git co .'
end